- name: "Evaluación de Seguridad: CIS PRO Level 1 Server (Ubuntu 22.04)"
  hosts: "all:!SLKVAWXTFGDES"
  become: yes
  gather_facts: yes
  vars:
    oscap_profile: "xccdf_org.cisecurity.benchmarks_profile_Level_1_-_Server"
    benchmark: "cis_server_l1_pro"
    cis_pro_source_dir: "/home/ibai/awx-poc-tfg/CIS-PRO-xml/ubn2204"
    cis_xccdf_file: "CIS_Ubuntu_Linux_22.04_LTS_Benchmark_v3.0.0-xccdf.xml"
    awx_report_base_dir: "/home/ibai/awx-poc-tfg/reportes"

  tasks:
  
    - name: "PREPARACIÓN | Instalar dependencias"
      ansible.builtin.apt:
        name: 
          - libopenscap8
          - openscap-scanner
          - tar
        state: present
        update_cache: yes

    - name: "SISTEMA DE ARCHIVOS | Crear directorios de escaneo"
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /tmp/openscap_reports
        - /tmp/openscap_reports/ubn2204_scan
        
        

    - name: "SISTEMA DE ARCHIVOS | Comprimir origen usando comando tar (Método simple)"
      ansible.builtin.command: "tar -czf /tmp/cis_ubn2204_pro.tgz -C {{ cis_pro_source_dir }} ."
      delegate_to: SLKVAWXTFGDES
      run_once: yes
      become: yes

    - name: "RED | Descargar a AWX"
      ansible.builtin.fetch:
        src: "/tmp/cis_ubn2204_pro.tgz"
        dest: "/tmp/cis_ubn2204_pro.tgz"
        flat: yes
      delegate_to: SLKVAWXTFGDES
      run_once: yes
      become: yes

    - name: "RED | Subir a objetivos"
      ansible.builtin.copy:
        src: "/tmp/cis_ubn2204_pro.tgz"
        dest: "/tmp/openscap_reports/cis_ubn2204_pro.tgz"

    - name: "SISTEMA DE ARCHIVOS | Descomprimir en objetivos"
      ansible.builtin.unarchive:
        src: "/tmp/openscap_reports/cis_ubn2204_pro.tgz"
        dest: "/tmp/openscap_reports/ubn2204_scan/"
        remote_src: yes

    - name: "EJECUCIÓN | Lanzar escaneo OpenSCAP"
      ansible.builtin.command: >
        oscap xccdf eval
        --profile {{ oscap_profile }}
        --results /tmp/openscap_reports/results.xml
        --report /tmp/openscap_reports/report.html
        {{ cis_xccdf_file }}
      args:
        chdir: "/tmp/openscap_reports/ubn2204_scan"
      register: oscap_scan
      failed_when: oscap_scan.rc not in [0, 2]

    - name: "PROCESAMIENTO | Bloque de reportes"
      block:
        - name: "VARIABLES | Set names"
          ansible.builtin.set_fact:
            os_ver: "{{ ansible_distribution | lower | replace(' ', '') | replace('linux', '') }}{{ ansible_distribution_version | replace('.', '') }}"
            target_name: "{{ inventory_hostname }}"
        
        - name: "VARIABLES | Set base"
          ansible.builtin.set_fact:
            file_base: "{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}T{{ ansible_date_time.minute }}-{{ os_ver }}-{{ benchmark }}-{{ target_name }}"

        - name: "RED | Fetch reportes"
          ansible.builtin.fetch:
            src: "/tmp/openscap_reports/{{ item }}"
            dest: "/tmp/{{ file_base }}.{{ item | splitext | last }}"
            flat: yes
          loop:
            - results.xml
            - report.html

        - name: "SISTEMA DE ARCHIVOS | Crear carpetas finales"
          ansible.builtin.file:
            path: "{{ awx_report_base_dir }}/{{ target_name }}/{{ item }}"
            state: directory
            mode: '0755'
          delegate_to: SLKVAWXTFGDES
          become: yes
          loop: ['xml', 'html']

        - name: "SISTEMA DE ARCHIVOS | Mover a final"
          ansible.builtin.copy:
            src: "/tmp/{{ file_base }}.{{ item }}"
            dest: "{{ awx_report_base_dir }}/{{ target_name }}/{{ item }}/{{ file_base }}.{{ item }}"
          delegate_to: SLKVAWXTFGDES
          loop: ['xml', 'html']

    - name: "EXTRACCIÓN | Score"
      ansible.builtin.shell: "awk -F'[><]' '/<score system=\"urn:xccdf:scoring:default\"/{print $3; exit}' {{ awx_report_base_dir }}/{{ target_name }}/xml/{{ file_base }}.xml"
      delegate_to: SLKVAWXTFGDES
      register: openscap_score
      changed_when: false
      become: yes

    - name: "RESUMEN"
      ansible.builtin.debug:
        msg: "COMPLETADO: {{ inventory_hostname }} | CUMPLIMIENTO: {{ openscap_score.stdout | float | round(2) }}%"

    - name: "LIMPIEZA | Nodos"
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      delegate_to: "{{ item.host }}"
      become: "{{ item.become }}"
      run_once: "{{ item.run_once }}"
      loop:
        - { path: '/tmp/openscap_reports', host: '{{ inventory_hostname }}', become: yes, run_once: no }
        - { path: '/tmp/cis_ubn2204_pro.tgz', host: 'localhost', become: no, run_once: yes }
        - { path: '/tmp/cis_ubn2204_pro.tgz', host: 'SLKVAWXTFGDES', become: yes, run_once: yes }
