---
- name: "Hardening Ubuntu 22.04 with CIS Benchmark Level {{ ubtu22cis_level }}"
  hosts: "all:!SLKVAWXTFGDES"
  become: true
  
  vars:
    # Safe defaults (will be overwritten by AWX Survey)
    ubtu22cis_level: 1
    ubtu22cis_disruption_high: false
    run_audit: false
    skip_reboot: true

  roles:
    - role: roles/UBUNTU22-CIS
