---
# Overrides for UBUNTU22-CIS Defaults

# Safety Settings
skip_reboot: true
ubtu22cis_disruption_high: false
run_audit: false
setup_audit: false

# Sudo Overrides
ubtu22cis_sudoers_exclude_nopasswd_list:
  - ansible_sshkey
  - ansible_passwd
  - lksistemas

# Disable Section 5.2 to protect local sudo access
ubtu22cis_rule_5_2_1: false 
ubtu22cis_rule_5_2_2: false 
ubtu22cis_rule_5_2_3: false 
ubtu22cis_rule_5_2_4: false 
ubtu22cis_rule_5_2_5: false 
ubtu22cis_rule_5_2_6: false 
ubtu22cis_rule_5_2_7: false
ubtu22cis_rule_5_4_2_4: false #mantener cuenta root bloqueada
# Skip the requirement to have a GRUB bootloader password set
ubtu22cis_rule_1_4_1: false

# Skip the requirement to have a manual root password set
ubtu22cis_rule_5_4_2_4: false
